# TCL File Generated by Component Editor 25.1
# Mon May 18 17:58:50 EDT 2026
# DO NOT MODIFY


# 
# accelerator "accelerator" v1.0
#  2026.05.18.17:58:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accelerator.sv SYSTEM_VERILOG PATH accelerator.sv TOP_LEVEL_FILE
add_fileset_file double_buffer.sv SYSTEM_VERILOG PATH double_buffer.sv
add_fileset_file mem.sv SYSTEM_VERILOG PATH mem.sv
add_fileset_file stage_f.sv SYSTEM_VERILOG PATH stage_f.sv
add_fileset_file stage_rmw.sv SYSTEM_VERILOG PATH stage_rmw.sv
add_fileset_file stage_t.sv SYSTEM_VERILOG PATH stage_t.sv
add_fileset_file sys_defs.svh OTHER PATH sys_defs.svh
add_fileset_file trig_lut.sv SYSTEM_VERILOG PATH trig_lut.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point hps_write_port
# 
add_interface hps_write_port avalon end
set_interface_property hps_write_port addressUnits WORDS
set_interface_property hps_write_port associatedClock clock
set_interface_property hps_write_port associatedReset reset_sink
set_interface_property hps_write_port bitsPerSymbol 8
set_interface_property hps_write_port burstOnBurstBoundariesOnly false
set_interface_property hps_write_port burstcountUnits WORDS
set_interface_property hps_write_port explicitAddressSpan 0
set_interface_property hps_write_port holdTime 0
set_interface_property hps_write_port linewrapBursts false
set_interface_property hps_write_port maximumPendingReadTransactions 0
set_interface_property hps_write_port maximumPendingWriteTransactions 0
set_interface_property hps_write_port readLatency 0
set_interface_property hps_write_port readWaitTime 1
set_interface_property hps_write_port setupTime 0
set_interface_property hps_write_port timingUnits Cycles
set_interface_property hps_write_port writeWaitTime 0
set_interface_property hps_write_port ENABLED true
set_interface_property hps_write_port EXPORT_OF ""
set_interface_property hps_write_port PORT_NAME_MAP ""
set_interface_property hps_write_port CMSIS_SVD_VARIABLES ""
set_interface_property hps_write_port SVD_ADDRESS_GROUP ""

add_interface_port hps_write_port hps_we write Input 1
add_interface_port hps_write_port hps_data_in_flat writedata Input 8
add_interface_port hps_write_port hps_write_addr address Input 14
set_interface_assignment hps_write_port embeddedsw.configuration.isFlash 0
set_interface_assignment hps_write_port embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps_write_port embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps_write_port embeddedsw.configuration.isPrintableDevice 0


# 
# connection point hps_read_port
# 
add_interface hps_read_port avalon end
set_interface_property hps_read_port addressUnits WORDS
set_interface_property hps_read_port associatedClock clock
set_interface_property hps_read_port associatedReset reset_sink
set_interface_property hps_read_port bitsPerSymbol 8
set_interface_property hps_read_port burstOnBurstBoundariesOnly false
set_interface_property hps_read_port burstcountUnits WORDS
set_interface_property hps_read_port explicitAddressSpan 0
set_interface_property hps_read_port holdTime 0
set_interface_property hps_read_port linewrapBursts false
set_interface_property hps_read_port maximumPendingReadTransactions 0
set_interface_property hps_read_port maximumPendingWriteTransactions 0
set_interface_property hps_read_port readLatency 0
set_interface_property hps_read_port readWaitTime 1
set_interface_property hps_read_port setupTime 0
set_interface_property hps_read_port timingUnits Cycles
set_interface_property hps_read_port writeWaitTime 0
set_interface_property hps_read_port ENABLED true
set_interface_property hps_read_port EXPORT_OF ""
set_interface_property hps_read_port PORT_NAME_MAP ""
set_interface_property hps_read_port CMSIS_SVD_VARIABLES ""
set_interface_property hps_read_port SVD_ADDRESS_GROUP ""

add_interface_port hps_read_port hps_read_addr address Input 14
add_interface_port hps_read_port hps_data_out_flat readdata Output 8
set_interface_assignment hps_read_port embeddedsw.configuration.isFlash 0
set_interface_assignment hps_read_port embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps_read_port embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps_read_port embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end data_in_flat data Input 74
add_interface_port conduit_end switch switch Input 1

